# -*- coding: utf-8 -*-
"""Zomato_Data.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rpNWUUlFd9qCaq545hJu8BHNvN3mDutH

# **Zomato Data Analysis Project**
1. Imorting Libraries
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

"""2. Create the data frame

"""

data =pd.read_csv('/content/Zomato data .csv')
print(data)

data.info()

data

"""3.  conert the data type of column - rate"""

def HandelRate(values):
  value=str(values).split("/")
  value=value[0];
  return float(value)

data['rate'] = data['rate'].apply(HandelRate)
data.head()

"""**Type Of Restaurant**"""

sns.countplot(x=data['listed_in(type)'])
plt.xlabel('Type Of Restaurant')

"""**Most restaurants are Dining, followed by Cafes. Buffet and Other types are the least common**


"""

grouped_data = data.groupby('listed_in(type)') ['votes'].sum()
result = pd.DataFrame({'votes': grouped_data})
plt.plot(result, c="Blue", marker="*")
plt.xlabel("Type of restaurant", c="Black", size=15)
plt.ylabel("Votes", c="Black", size=15)

"""**Dining restaurants are the most preferred by voters, while Buffet has the least votes. Other restaurant types have moderate popularity.**"""

sns.histplot(data['rate'], bins=15)
plt.title('Distribution of Restaurant Ratings')
plt.show()

"""**Most restaurants have ratings between 3.0 and 4.0 with 4.0 being the most common Very high and very low ratings are rare.**"""

data.head()

couple_data=data['approx_cost(for two people)']
sns.countplot(x=couple_data)

"""**Most restaurants have an average cost between ₹200 and ₹500** for two people, with **₹300 being the most frequent Expensive options are less common.**

**Which Mode Recieved Max Rating**
"""

plt.figure(figsize = (6,6))
sns.boxplot(x = 'online_order', y = 'rate', data=data)

"""**Restaurants with online ordering tend to receive better ratings**


---


"""

#pivot_table = data.pivot_table(index='listed_in(type)', columns='online_order')
pivot_table = data.pivot_table(index='listed_in(type)',columns='online_order',values='rate',aggfunc='mean')
sns.heatmap(pivot_table, annot=True, cmap="YlGnBu", fmt='.2f')
plt.title("Heatmap")
plt.xlabel("Online Order")
plt.ylabel("Listed In (Type)")
plt.show()

"""**Restaurants with online ordering tend to receive better ratings, suggesting it enhances customer satisfaction**"""

